version: '3.8'

services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: attendwise_postgres
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - attendwise-net
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: attendwise_pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#     ports:
#       - "5050:80"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     networks:
#       - attendwise-net
#     restart: unless-stopped

  # neo4j:
  #   image: neo4j:5-enterprise
  #   container_name: attendwise_neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - neo4j_data:/data
  #   environment:
  #     - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
  #     - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  #     - NEO4J_PLUGINS=["apoc", "graph-data-science"]
  #   networks:
  #     - attendwise-net
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME} -p ${NEO4J_PASSWORD} 'RETURN 1'"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

#   minio:
#     image: minio/minio:RELEASE.2023-09-07T02-05-02Z
#     container_name: attendwise_minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio_data:/data
#     environment:
#       MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#       MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#     command: server /data --console-address ":9001"
#     networks:
#       - attendwise-net
#     restart: unless-stopped

  nats:
    image: nats:2.10-alpine
    container_name: attendwise_nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - attendwise-net
    restart: unless-stopped

  # redis:
  #   image: redis:alpine
  #   container_name: attendwise_redis
  #   ports:
  #     - "6380:6379"
  #   networks:
  #     - attendwise-net
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendwise_api_gateway
    ports:
      - "8080:8080"
    depends_on:
      # neo4j:
      #   condition: service_healthy
      nats:
        condition: service_started
      # redis:
      #   condition: service_healthy
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
#       - MINIO_ENDPOINT=minio:9000
#       - MINIO_ACCESS_KEY_ID=${MINIO_ROOT_USER}
#       - MINIO_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
#       - MINIO_USE_SSL=${MINIO_USE_SSL}
#       - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - GRPC_AI_SERVICE_ADDR=ai-service:50051
      - API_GATEWAY_PORT=8080
      - NATS_URL=nats://nats:4222
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - MIGRATIONS_PATH=file:///home/appuser/migrations
      - COOKIE_DOMAIN=attendwise-website-1cud.onrender.com
      
    networks:
      - attendwise-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

# ai-service:
#     build:
#       context: ./backend/ai-service
#       dockerfile: Dockerfile
#     container_name: attendwise_ai_service
#     ports:
#       - "50051:50051"
#     networks:
#       - attendwise-net
#     restart: unless-stopped

volumes:
  postgres_data:
  neo4j_data:
#  minio_data:

networks:
  attendwise-net:
    driver: bridge